export const ACHIEVEMENT_DEFINITIONS = [
  {
    code: 'first_completion',
    name: 'First Blood',
    icon: '⚔️',
    description: 'Complete your first habit',
    xpReward: 50,
    category: 'general',
    condition: { type: 'totalHabitsCompleted_gte', threshold: 1 },
  },
  {
    code: 'complete_10',
    name: 'Dedicated',
    icon: '🌱',
    description: 'Complete 10 habits',
    xpReward: 75,
    category: 'general',
    condition: { type: 'totalHabitsCompleted_gte', threshold: 10 },
  },
  {
    code: 'complete_50',
    name: 'Committed',
    icon: '🔥',
    description: 'Complete 50 habits',
    xpReward: 150,
    category: 'general',
    condition: { type: 'totalHabitsCompleted_gte', threshold: 50 },
  },
  {
    code: 'reach_level_5',
    name: 'Apprentice',
    icon: '⭐',
    description: 'Reach Level 5',
    xpReward: 100,
    category: 'milestone',
    condition: { type: 'level_gte', threshold: 5 },
  },
  {
    code: 'reach_level_10',
    name: 'Journeyman',
    icon: '🌟',
    description: 'Reach Level 10',
    xpReward: 200,
    category: 'milestone',
    condition: { type: 'level_gte', threshold: 10 },
  },
  {
    code: 'streak_3',
    name: 'On a Roll',
    icon: '🔥',
    description: '3-day streak on any habit',
    xpReward: 75,
    category: 'general',
    condition: { type: 'anyStreakCurrent_gte', threshold: 3 },
  },
  {
    code: 'streak_7',
    name: 'Week Warrior',
    icon: '🗓️',
    description: '7-day streak on any habit',
    xpReward: 150,
    category: 'general',
    condition: { type: 'anyStreakCurrent_gte', threshold: 7 },
  },
] as const;
